# Generated by Django 4.2.7 on 2024-03-14 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('currently_in', models.CharField(max_length=100)),
                ('school', models.CharField(max_length=250)),
                ('mobile_no', models.CharField(max_length=12)),
                ('roll_no', models.CharField(max_length=12)),
                ('hindi', models.IntegerField()),
                ('english', models.IntegerField()),
                ('science', models.IntegerField()),
                ('social_science', models.IntegerField()),
                ('maths', models.IntegerField()),
                ('computer', models.IntegerField()),
                ('status', models.CharField(max_length=100)),
            ],
        ),
    ]
